# Generated by Django 5.1.6 on 2025-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
